name: 小张の日常生活  Dailylife of Ms. Zhang
url: https://xiaohang007.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: exercise
    name: 运动 Exercise
  - key: music
    name: 音乐 Music
  - key: film
    name: 电影 Film
  - key: TV Show
    name: 电视剧 TV Show


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 关于我 About Me
    link: /
  - title: 兴趣 Hobby
    link: /research.html
  - title: 日常 Dailylife
    link: /publications.html
